/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author unifmgomes
 */
public class ExibirSaldoCliente extends javax.swing.JFrame {

    /**
     * Creates new form ExibirSaldo
     */
    public ExibirSaldoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpfClienteDebitarTXT = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        tituloExibirSaldoCliente1 = new javax.swing.JLabel();
        senhaClienteExibirSaldoTXT = new javax.swing.JLabel();
        cpfClienteExibirSaldoEntrada = new javax.swing.JTextField();
        senhaClienteExibirSaldoEntrada = new javax.swing.JTextField();
        cpfClienteExibirSaldoTXT = new javax.swing.JLabel();
        butClienteExibirSaldo = new javax.swing.JButton();

        cpfClienteDebitarTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpfClienteDebitarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpfClienteDebitarTXT.setText("CPF:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloExibirSaldoCliente1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloExibirSaldoCliente1.setText("Exibir Saldo:");

        senhaClienteExibirSaldoTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senhaClienteExibirSaldoTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senhaClienteExibirSaldoTXT.setText("Senha:");

        cpfClienteExibirSaldoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfClienteExibirSaldoEntradaActionPerformed(evt);
            }
        });

        senhaClienteExibirSaldoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaClienteExibirSaldoEntradaActionPerformed(evt);
            }
        });

        cpfClienteExibirSaldoTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpfClienteExibirSaldoTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpfClienteExibirSaldoTXT.setText("CPF:");

        butClienteExibirSaldo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        butClienteExibirSaldo.setText("Exibir Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpfClienteExibirSaldoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaClienteExibirSaldoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cpfClienteExibirSaldoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(tituloExibirSaldoCliente1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(butClienteExibirSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(senhaClienteExibirSaldoEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloExibirSaldoCliente1)
                .addGap(50, 50, 50)
                .addComponent(cpfClienteExibirSaldoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfClienteExibirSaldoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(senhaClienteExibirSaldoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaClienteExibirSaldoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(butClienteExibirSaldo)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfClienteExibirSaldoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfClienteExibirSaldoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfClienteExibirSaldoEntradaActionPerformed

    private void senhaClienteExibirSaldoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaClienteExibirSaldoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaClienteExibirSaldoEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ExibirSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ExibirSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ExibirSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ExibirSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ExibirSaldo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butClienteExibirSaldo;
    private javax.swing.JLabel cpfClienteDebitarTXT;
    private javax.swing.JTextField cpfClienteExibirSaldoEntrada;
    private javax.swing.JLabel cpfClienteExibirSaldoTXT;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField senhaClienteExibirSaldoEntrada;
    private javax.swing.JLabel senhaClienteExibirSaldoTXT;
    private javax.swing.JLabel tituloExibirSaldoCliente1;
    // End of variables declaration//GEN-END:variables
}
