/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerEscolherContaCliente;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.Cliente;

/**
 *
 * @author iago2
 */
public class EscolherConta extends javax.swing.JFrame {

    /**
     * Creates new form EscolherConta
     */
    public EscolherConta(Cliente cliente) {
        initComponents();
        controller = new ControllerEscolherContaCliente(this, cliente.getCpf());
    }

    public JButton getBtContaCorrenteCriar() {
        return btContaCorrenteCriar;
    }

    public void setBtContaCorrenteCriar(JButton btContaCorrenteCriar) {
        this.btContaCorrenteCriar = btContaCorrenteCriar;
    }

    public JButton getBtContaPoupancaCriar() {
        return btContaPoupancaCriar;
    }

    public void setBtContaPoupancaCriar(JButton btContaPoupancaCriar) {
        this.btContaPoupancaCriar = btContaPoupancaCriar;
    }

    public JButton getBtContaSalarioCriar() {
        return btContaSalarioCriar;
    }

    public void setBtContaSalarioCriar(JButton btContaSalarioCriar) {
        this.btContaSalarioCriar = btContaSalarioCriar;
    }

    public JLabel getLbCriarConta() {
        return lbCriarConta;
    }

    public void setLbCriarConta(JLabel lbCriarConta) {
        this.lbCriarConta = lbCriarConta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btContaCorrenteCriar1 = new javax.swing.JButton();
        lbCriarConta = new javax.swing.JLabel();
        btContaPoupancaCriar = new javax.swing.JButton();
        btContaCorrenteCriar = new javax.swing.JButton();
        btContaSalarioCriar = new javax.swing.JButton();

        btContaCorrenteCriar1.setText("Conta Corrente");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbCriarConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCriarConta.setText("Criar Conta");

        btContaPoupancaCriar.setText("Conta Poupança");
        btContaPoupancaCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaPoupancaCriarActionPerformed(evt);
            }
        });

        btContaCorrenteCriar.setText("Conta Corrente");
        btContaCorrenteCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaCorrenteCriarActionPerformed(evt);
            }
        });

        btContaSalarioCriar.setText("Conta Salário");
        btContaSalarioCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaSalarioCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCriarConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btContaPoupancaCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btContaCorrenteCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btContaSalarioCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbCriarConta)
                .addGap(38, 38, 38)
                .addComponent(btContaPoupancaCriar)
                .addGap(18, 18, 18)
                .addComponent(btContaCorrenteCriar)
                .addGap(18, 18, 18)
                .addComponent(btContaSalarioCriar)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContaPoupancaCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaPoupancaCriarActionPerformed
        // TODO add your handling code here:
        controller.contaPoupanca();
    }//GEN-LAST:event_btContaPoupancaCriarActionPerformed

    private void btContaCorrenteCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaCorrenteCriarActionPerformed
        // TODO add your handling code here:
        controller.contaCorrente();
    }//GEN-LAST:event_btContaCorrenteCriarActionPerformed

    private void btContaSalarioCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaSalarioCriarActionPerformed
        // TODO add your handling code here:
        controller.contaSalario();
    }//GEN-LAST:event_btContaSalarioCriarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EscolherConta().setVisible(true);
//            }
//        });
//    }

    // Instânciando controller.
    private ControllerEscolherContaCliente controller;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContaCorrenteCriar;
    private javax.swing.JButton btContaCorrenteCriar1;
    private javax.swing.JButton btContaPoupancaCriar;
    private javax.swing.JButton btContaSalarioCriar;
    private javax.swing.JLabel lbCriarConta;
    // End of variables declaration//GEN-END:variables
}
