/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerPaginasMenuGerente;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.Gerente;

/**
 *
 * @author iago2
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente(Gerente gerente) {
        initComponents();
        controller = new ControllerPaginasMenuGerente(this);
    }

    public JButton getBtCadastrarCliente() {
        return btCadastrarCliente;
    }

    public void setBtCadastrarCliente(JButton btCadastrarCliente) {
        this.btCadastrarCliente = btCadastrarCliente;
    }

    public JButton getBtCriarConta() {
        return btCriarConta;
    }

    public void setBtCriarConta(JButton btCriarConta) {
        this.btCriarConta = btCriarConta;
    }

    public JButton getBtExcluirCliente() {
        return btExcluirCliente;
    }

    public void setBtExcluirCliente(JButton btExcluirCliente) {
        this.btExcluirCliente = btExcluirCliente;
    }

    public JButton getBtExibirContas() {
        return btExibirContas;
    }

    public void setBtExibirContas(JButton btExibirContas) {
        this.btExibirContas = btExibirContas;
    }

    public JButton getBtExibirSaldo() {
        return btExibirSaldo;
    }

    public void setBtExibirSaldo(JButton btExibirSaldo) {
        this.btExibirSaldo = btExibirSaldo;
    }

    public JLabel getLbMenuGerente() {
        return lbMenuGerente;
    }

    public void setLbMenuGerente(JLabel lbMenuGerente) {
        this.lbMenuGerente = lbMenuGerente;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrarCliente = new javax.swing.JButton();
        btExcluirCliente = new javax.swing.JButton();
        btCriarConta = new javax.swing.JButton();
        btExibirContas = new javax.swing.JButton();
        btExibirSaldo = new javax.swing.JButton();
        lbMenuGerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCadastrarCliente.setText("Cadastrar Cliente");
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });

        btExcluirCliente.setText("Excluir Cliente");
        btExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirClienteActionPerformed(evt);
            }
        });

        btCriarConta.setText("Criar Conta");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });

        btExibirContas.setText("Exibir Contas");
        btExibirContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExibirContasActionPerformed(evt);
            }
        });

        btExibirSaldo.setText("Exibir Saldo");
        btExibirSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExibirSaldoActionPerformed(evt);
            }
        });

        lbMenuGerente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbMenuGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuGerente.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenuGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExibirSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExibirContas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarCliente))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lbMenuGerente)
                .addGap(18, 18, 18)
                .addComponent(btCadastrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCriarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExibirContas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExibirSaldo)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed
        // TODO add your handling code here:
        controller.entrarCadastrarCliente();
    }//GEN-LAST:event_btCadastrarClienteActionPerformed

    private void btExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirClienteActionPerformed
        // TODO add your handling code here:
        controller.entrarExcluirCliente();
    }//GEN-LAST:event_btExcluirClienteActionPerformed

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        // TODO add your handling code here:
        controller.entrarCriarConta();
    }//GEN-LAST:event_btCriarContaActionPerformed

    private void btExibirContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExibirContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExibirContasActionPerformed

    private void btExibirSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExibirSaldoActionPerformed
        // TODO add your handling code here:
        controller.entrarExibirSaldo();
    }//GEN-LAST:event_btExibirSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuGerente().setVisible(true);
//            }
//        });
//    }

    private ControllerPaginasMenuGerente controller;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btCriarConta;
    private javax.swing.JButton btExcluirCliente;
    private javax.swing.JButton btExibirContas;
    private javax.swing.JButton btExibirSaldo;
    private javax.swing.JLabel lbMenuGerente;
    // End of variables declaration//GEN-END:variables
}
