/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerValorInicialCliente;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Cliente;

/**
 *
 * @author iago2
 */
public class ValorInicial extends javax.swing.JFrame {

    /**
     * Creates new form ValorInicial
     */
    public ValorInicial(Cliente cliente) {
        initComponents();
        controller = new ControllerValorInicialCliente(this, cliente.getCpf());
    }

    public JButton getBtCriarConta() {
        return btCriarConta;
    }

    public void setBtCriarConta(JButton btCriarConta) {
        this.btCriarConta = btCriarConta;
    }

    public JLabel getLbCriarConta() {
        return lbCriarConta;
    }

    public void setLbCriarConta(JLabel lbCriarConta) {
        this.lbCriarConta = lbCriarConta;
    }

    public JLabel getLbValorInicial() {
        return lbValorInicial;
    }

    public void setLbValorInicial(JLabel lbValorInicial) {
        this.lbValorInicial = lbValorInicial;
    }

    public JTextField getTxtEntradaValorInicialCriar() {
        return txtEntradaValorInicialCriar;
    }

    public void setTxtEntradaValorInicialCriar(JTextField txtEntradaValorInicialCriar) {
        this.txtEntradaValorInicialCriar = txtEntradaValorInicialCriar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCriarConta = new javax.swing.JLabel();
        lbValorInicial = new javax.swing.JLabel();
        txtEntradaValorInicialCriar = new javax.swing.JTextField();
        btCriarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbCriarConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCriarConta.setText("Criar Conta");

        lbValorInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorInicial.setText("Valor inicial:");

        txtEntradaValorInicialCriar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaValorInicialCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaValorInicialCriarActionPerformed(evt);
            }
        });

        btCriarConta.setText("Criar");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCriarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCriarConta)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txtEntradaValorInicialCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lbValorInicial)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbCriarConta)
                .addGap(38, 38, 38)
                .addComponent(lbValorInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntradaValorInicialCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCriarConta)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaValorInicialCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaValorInicialCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaValorInicialCriarActionPerformed

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        // TODO add your handling code here:
        controller.valorInicial();
    }//GEN-LAST:event_btCriarContaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ValorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ValorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ValorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ValorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ValorInicial().setVisible(true);
//            }
//        });
//    }
    
    // Instânciando controller.
    private ControllerValorInicialCliente controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarConta;
    private javax.swing.JLabel lbCriarConta;
    private javax.swing.JLabel lbValorInicial;
    private javax.swing.JTextField txtEntradaValorInicialCriar;
    // End of variables declaration//GEN-END:variables
}
